export interface StatisticsStudyItem {
    term: string;
    plainEnglish: string;
    quickFormula: string;
    whyItMatters: string;
}

export const statisticsStudyGuide: StatisticsStudyItem[] = [
    { term: 'Mean', plainEnglish: 'Average value of a dataset.', quickFormula: 'sum(x) / n', whyItMatters: 'Daily return averages help summarize overall portfolio drift.' },
    { term: 'Median', plainEnglish: 'Middle value after sorting.', quickFormula: 'middle(sorted x)', whyItMatters: 'Less sensitive than mean when a few days are extreme.' },
    { term: 'Mode', plainEnglish: 'Most frequent value.', quickFormula: 'argmax frequency(x)', whyItMatters: 'Useful for spotting repeated transaction sizes or behaviors.' },
    { term: 'Range', plainEnglish: 'Distance between max and min values.', quickFormula: 'max(x) - min(x)', whyItMatters: 'Shows rough spread of prices or returns quickly.' },
    { term: 'Variance', plainEnglish: 'Average squared distance from the mean.', quickFormula: 'sum((x - mean)^2) / (n - 1)', whyItMatters: 'Core measure behind volatility and many risk metrics.' },
    { term: 'Standard Deviation', plainEnglish: 'Typical distance from the mean.', quickFormula: 'sqrt(variance)', whyItMatters: 'Directly interpretable risk scale for return dispersion.' },
    { term: 'Coefficient of Variation', plainEnglish: 'Risk per unit of average return level.', quickFormula: 'std(x) / abs(mean(x))', whyItMatters: 'Compares relative volatility across different assets.' },
    { term: 'Percentile', plainEnglish: 'Value below which a chosen percent of data falls.', quickFormula: 'Q(p)', whyItMatters: 'Useful for setting thresholds like worst 5% outcomes.' },
    { term: 'Quartile (Q1/Q2/Q3)', plainEnglish: '25th, 50th, and 75th percentile markers.', quickFormula: 'Q1=Q(0.25), Q2=Q(0.50), Q3=Q(0.75)', whyItMatters: 'Summarizes return distribution in robust chunks.' },
    { term: 'Interquartile Range', plainEnglish: 'Spread of the middle 50% of values.', quickFormula: 'Q3 - Q1', whyItMatters: 'Stable spread metric when tails are noisy.' },
    { term: 'Z-Score', plainEnglish: 'How many standard deviations a value is from mean.', quickFormula: '(x - mean) / std', whyItMatters: 'Flags unusually large gain or loss days.' },
    { term: 'Outlier', plainEnglish: 'Value far from the typical pattern.', quickFormula: 'often |z| > 3', whyItMatters: 'Highlights rare shocks that can distort analysis.' },
    { term: 'Skewness', plainEnglish: 'Asymmetry of a distribution.', quickFormula: 'E[((x - mean)/std)^3]', whyItMatters: 'Negative skew warns about heavier downside tail risk.' },
    { term: 'Excess Kurtosis', plainEnglish: 'How heavy tails are relative to normal.', quickFormula: 'E[((x - mean)/std)^4] - 3', whyItMatters: 'Higher values imply more extreme return events.' },
    { term: 'Covariance', plainEnglish: 'How two variables move together.', quickFormula: 'E[(x - meanX)(y - meanY)]', whyItMatters: 'Foundation for diversification analysis across stocks.' },
    { term: 'Correlation', plainEnglish: 'Standardized covariance from -1 to +1.', quickFormula: 'cov(x,y) / (stdX*stdY)', whyItMatters: 'Quickly checks whether positions move in sync.' },
    { term: 'Linear Regression', plainEnglish: 'Best-fit line relating predictor and outcome.', quickFormula: 'y = a + b*x', whyItMatters: 'Used for trend estimation and directional signal checks.' },
    { term: 'Slope', plainEnglish: 'Rate of change of the fitted line.', quickFormula: 'b in y = a + b*x', whyItMatters: 'Positive slope indicates upward trend in series.' },
    { term: 'Intercept', plainEnglish: 'Predicted y-value when x is zero.', quickFormula: 'a in y = a + b*x', whyItMatters: 'Baseline level in simple trend models.' },
    { term: 'R-Squared', plainEnglish: 'Share of variance explained by model.', quickFormula: '1 - SSR/SST', whyItMatters: 'Shows how strong linear trend fit really is.' },
    { term: 'Residual', plainEnglish: 'Difference between actual and predicted value.', quickFormula: 'e = y - yHat', whyItMatters: 'Large residuals indicate model miss or new regime.' },
    { term: 'Null Hypothesis', plainEnglish: 'Default claim that effect is zero.', quickFormula: 'H0: parameter = 0', whyItMatters: 'Provides baseline before claiming strategy edge.' },
    { term: 'Alternative Hypothesis', plainEnglish: 'Claim that an effect exists.', quickFormula: 'H1: parameter != 0', whyItMatters: 'Represents your signal or alpha hypothesis.' },
    { term: 'P-Value', plainEnglish: 'Probability of seeing data this extreme under H0.', quickFormula: 'p = P(test statistic as extreme | H0)', whyItMatters: 'Helps avoid over-trusting random patterns.' },
    { term: 'Type I Error', plainEnglish: 'False positive: rejecting true H0.', quickFormula: 'alpha', whyItMatters: 'Too many false signals can cause overtrading.' },
    { term: 'Type II Error', plainEnglish: 'False negative: missing real effect.', quickFormula: 'beta', whyItMatters: 'Can hide profitable but subtle opportunities.' },
    { term: 'Confidence Interval', plainEnglish: 'Range likely containing true parameter.', quickFormula: 'estimate +/- critical * SE', whyItMatters: 'Conveys uncertainty around return estimates.' },
    { term: 'Margin of Error', plainEnglish: 'Half-width of confidence interval.', quickFormula: 'critical * SE', whyItMatters: 'Shows precision quality of your estimates.' },
    { term: 'Standard Error', plainEnglish: 'Expected variability of estimator.', quickFormula: 'std / sqrt(n)', whyItMatters: 'Smaller SE means more stable measured edge.' },
    { term: 'Sample Size', plainEnglish: 'Number of observations used in analysis.', quickFormula: 'n', whyItMatters: 'Small n can make metrics unstable and misleading.' },
    { term: 'Law of Large Numbers', plainEnglish: 'Averages stabilize as sample size grows.', quickFormula: 'mean_n -> expected value', whyItMatters: 'Longer history makes return estimates more reliable.' },
    { term: 'Central Limit Theorem', plainEnglish: 'Sample means approach normality for large n.', quickFormula: 'sqrt(n)(mean - mu) -> Normal', whyItMatters: 'Justifies many interval and test approximations.' },
    { term: 'Stationarity', plainEnglish: 'Statistical properties stay roughly constant over time.', quickFormula: 'mean/variance stable across time', whyItMatters: 'Many time-series models assume this condition.' },
    { term: 'Autocorrelation', plainEnglish: 'Correlation of a series with its own lagged values.', quickFormula: 'corr(x_t, x_t-k)', whyItMatters: 'Detects momentum or mean-reversion patterns.' },
    { term: 'Simple Return', plainEnglish: 'Percent change between two prices.', quickFormula: '(P_t - P_{t-1}) / P_{t-1}', whyItMatters: 'Primary daily performance measure in the dashboard.' },
    { term: 'Log Return', plainEnglish: 'Continuously compounded return.', quickFormula: 'ln(P_t / P_{t-1})', whyItMatters: 'Adds cleanly over time and works well in models.' },
    { term: 'Cumulative Return', plainEnglish: 'Total compounded return over a period.', quickFormula: 'prod(1 + r_t) - 1', whyItMatters: 'Summarizes end-to-end growth of a strategy.' },
    { term: 'Moving Average', plainEnglish: 'Rolling mean over a fixed window.', quickFormula: 'MA_t = mean(x_{t-w+1...t})', whyItMatters: 'Smooths noise to reveal trend direction.' },
    { term: 'Exponential Moving Average', plainEnglish: 'Weighted average emphasizing recent points.', quickFormula: 'EMA_t = alpha*x_t + (1-alpha)*EMA_{t-1}', whyItMatters: 'Responds faster to current market shifts.' },
    { term: 'Volatility', plainEnglish: 'Magnitude of return fluctuations.', quickFormula: 'std(returns)', whyItMatters: 'Core risk estimate used throughout analytics.' },
    { term: 'Annualized Volatility', plainEnglish: 'Volatility scaled to one year.', quickFormula: 'dailyVol * sqrt(252)', whyItMatters: 'Makes risk comparable with annual performance figures.' },
    { term: 'Drawdown', plainEnglish: 'Decline from prior peak value.', quickFormula: '(value - runningPeak) / runningPeak', whyItMatters: 'Tracks pain during losing periods.' },
    { term: 'Maximum Drawdown', plainEnglish: 'Worst observed drawdown over period.', quickFormula: 'min(drawdown_t)', whyItMatters: 'Critical downside risk metric for position sizing.' },
    { term: 'Value at Risk (VaR)', plainEnglish: 'Loss threshold not exceeded with chosen confidence.', quickFormula: 'VaR_95 = quantile(returns, 5%)', whyItMatters: 'Gives quick estimate of bad-day risk.' },
    { term: 'Conditional VaR (CVaR)', plainEnglish: 'Average loss beyond the VaR cutoff.', quickFormula: 'mean(returns <= VaR cutoff)', whyItMatters: 'Captures tail severity better than VaR alone.' },
    { term: 'Sharpe Ratio', plainEnglish: 'Excess return per unit of total risk.', quickFormula: '(meanR - rf) / stdR', whyItMatters: 'Balances reward and volatility in one score.' },
    { term: 'Sortino Ratio', plainEnglish: 'Excess return per unit of downside risk only.', quickFormula: '(meanR - rf) / downsideStd', whyItMatters: 'Focuses on harmful volatility instead of all volatility.' },
    { term: 'Beta', plainEnglish: 'Sensitivity of asset return to market return.', quickFormula: 'cov(asset, market) / var(market)', whyItMatters: 'Shows how strongly holdings react to market moves.' },
    { term: 'Monte Carlo Simulation', plainEnglish: 'Randomly simulate many possible future paths.', quickFormula: 'simulate N scenarios and summarize outcomes', whyItMatters: 'Stress-tests strategy under uncertain futures.' },
    { term: 'Bootstrap Resampling', plainEnglish: 'Sample with replacement from observed data.', quickFormula: 'resample dataset B times', whyItMatters: 'Estimates uncertainty without strict distribution assumptions.' },
    { term: 'Bayesian Update', plainEnglish: 'Update belief after observing new evidence.', quickFormula: 'posterior proportional prior * likelihood', whyItMatters: 'Supports adaptive decision-making as new data arrives.' }
];